apiVersion: apps/v1
kind: Deployment
metadata:
  name: product2.0
spec:
  replicas: 3
  selector:
    matchLabels:
      app: product-catalog
  template:
    metadata:
      labels:
        app: product-catalog
    spec:
      containers:
      - name: product2
        image: 1jashshah/product2
        ports:
        - containerPort: 80
